name: Publish

on:
  push:
    branches: [master]
    paths:
      - "**/template.yaml"
      - "**/template.yml"
jobs:
  Publish:
    name: publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.PUBLISH_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.PUBLISH_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
          
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v37

      - name: Upload integrations files to s3
        run: |
          changed_files_string="${{ steps.changed-files.outputs.all_changed_files }}"
          read -ra changed_files_array <<< "$changed_files_string"
          for changed_template in "${changed_files_array[@]}"; do
            if [[ $changed_template == */template.* ]]; then
              aws s3 cp  $changed_template s3://cgx-cloudformation-templates/${changed_template}
            fi
          done
